- shell:
      - [dnf -y install dnf-plugins-core, Install dnf-plugins-core...]
      - [
            dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo,
        ]
      - [
            dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin,
            Installing docker...,
        ]
      - [systemctl start docker, Starting docker service...]
